package org.omicron.apps.orm;
// Generated 20/12/2015 11:39:27 PM by Hibernate Tools 4.3.1.Final

/**
 * Domicilio generated by hbm2java
 */
public class Domicilio implements java.io.Serializable {

	private Integer codigo;
	private Usuarios usuarios;
	private String calle;
	private String numeroExterior;
	private String numeroInterior;
	private String colonia;
	private String cp;
	private String ciudad;
	private String municipio;
	private String estado;
	private String pais;

	public Domicilio() {
	}

	public Domicilio(Usuarios usuarios, String calle, String numeroExterior, String colonia, String cp, String ciudad,
		String estado, String pais) {
		this.usuarios = usuarios;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.colonia = colonia;
		this.cp = cp;
		this.ciudad = ciudad;
		this.estado = estado;
		this.pais = pais;
	}

	public Domicilio(Usuarios usuarios, String calle, String numeroExterior, String numeroInterior, String colonia,
		String cp, String ciudad, String municipio, String estado, String pais) {
		this.usuarios = usuarios;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.numeroInterior = numeroInterior;
		this.colonia = colonia;
		this.cp = cp;
		this.ciudad = ciudad;
		this.municipio = municipio;
		this.estado = estado;
		this.pais = pais;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

}
