package org.omicron.apps.orm;
// Generated 20/12/2015 11:39:27 PM by Hibernate Tools 4.3.1.Final

/**
 * PrestamosId generated by hbm2java
 */
public class PrestamosId implements java.io.Serializable {

	private int noPedido;
	private int usuariosCodigo;
	private int librosCodigo;

	public PrestamosId() {
	}

	public PrestamosId(int noPedido, int usuariosCodigo, int librosCodigo) {
		this.noPedido = noPedido;
		this.usuariosCodigo = usuariosCodigo;
		this.librosCodigo = librosCodigo;
	}

	public int getNoPedido() {
		return this.noPedido;
	}

	public void setNoPedido(int noPedido) {
		this.noPedido = noPedido;
	}

	public int getUsuariosCodigo() {
		return this.usuariosCodigo;
	}

	public void setUsuariosCodigo(int usuariosCodigo) {
		this.usuariosCodigo = usuariosCodigo;
	}

	public int getLibrosCodigo() {
		return this.librosCodigo;
	}

	public void setLibrosCodigo(int librosCodigo) {
		this.librosCodigo = librosCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrestamosId))
			return false;
		PrestamosId castOther = (PrestamosId) other;

		return (this.getNoPedido() == castOther.getNoPedido())
			&& (this.getUsuariosCodigo() == castOther.getUsuariosCodigo())
			&& (this.getLibrosCodigo() == castOther.getLibrosCodigo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNoPedido();
		result = 37 * result + this.getUsuariosCodigo();
		result = 37 * result + this.getLibrosCodigo();
		return result;
	}

}
