package org.omicron.apps.orm;
// Generated 20/12/2015 11:39:27 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private String apepat;
	private String apemat;
	private Date fechaNacimiento;
	private Set<Prestamos> prestamoses = new HashSet<Prestamos>(0);
	private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String apepat, String apemat, Date fechaNacimiento) {
		this.nombre = nombre;
		this.apepat = apepat;
		this.apemat = apemat;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Usuarios(String nombre, String apepat, String apemat, Date fechaNacimiento, Set<Prestamos> prestamoses,
		Set<Domicilio> domicilios) {
		this.nombre = nombre;
		this.apepat = apepat;
		this.apemat = apemat;
		this.fechaNacimiento = fechaNacimiento;
		this.prestamoses = prestamoses;
		this.domicilios = domicilios;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApepat() {
		return this.apepat;
	}

	public void setApepat(String apepat) {
		this.apepat = apepat;
	}

	public String getApemat() {
		return this.apemat;
	}

	public void setApemat(String apemat) {
		this.apemat = apemat;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Set<Prestamos> getPrestamoses() {
		return this.prestamoses;
	}

	public void setPrestamoses(Set<Prestamos> prestamoses) {
		this.prestamoses = prestamoses;
	}

	public Set<Domicilio> getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Set<Domicilio> domicilios) {
		this.domicilios = domicilios;
	}

}
